export enum CardStatus {
  SUBMITTED = 'SUBMITTED',

  FIRST_STAGE = 'FIRST_STAGE',

  SECOND_STAGE = 'SECOND_STAGE',

  FINAL_STAGE = 'FINAL_STAGE',

  REJECTED = 'REJECTED',

  ACCEPTED = 'ACCEPTED',
}
