export enum ContentType {
  AGRICULTURE = 'AGRICULTURE',

  CONSTRUCTION = 'CONSTRUCTION',

  HEALTHCARE = 'HEALTHCARE',

  TECHNOLOGY = 'TECHNOLOGY',

  FINANCE = 'FINANCE',

  ENTERTAINMENT = 'ENTERTAINMENT',

  TRANSPORT = 'TRANSPORT',

  MEDIA = 'MEDIA',

  ENGINEERING = 'ENGINEERING',

  PHARMACEUTICAL = 'PHARMACEUTICAL',

  RETAIL = 'RETAIL',

  CHEMICAL = 'CHEMICAL',

  INTERVIEW = 'INTERVIEW',

  ASSESSMENT = 'ASSESSMENT',

  LAW = 'LAW',
}
